### ISSUE TITLE
Error sort_by

### ISSUE THREAD

**Issue by ToloRiera** [bstascavage/plexReport#32]
Hello, I love this script!
I had a permissions issue ("Log file not found Exiting ....") I've solved temporarily.
Applying changing permissions "chmod -R 775" to plexReport directory permissions. What Should I apply?
With this problem fixed, another new problem appears when I run the script:

```
/home/tolo/plexReport/bin/plexReport.rb:189:in `sort_by': comparison of NilClass with String failed (ArgumentError)
	from /home/tolo/plexReport/bin/plexReport.rb:189:in `sort_by!'
	from /home/tolo/plexReport/bin/plexReport.rb:189:in `getTVEpisodes'
	from /home/tolo/plexReport/bin/plexReport.rb:317:in `main'
	from /home/tolo/plexReport/bin/plexReport.rb:335:in `<main>'
```
I searched the line of code fails and That is: (in case you help)

```
# Method for getting new TV shows from the Plx server  
    def getTVEpisodes
        plex = Plex.new($config)
        tv_episodes = Hash.new
        tv_episodes[:new] = []
        tv_episodes[:seasons] = []
 
        library = plex.get('/library/sections')
        library['MediaContainer']['Directory'].each do | element |
            if element['type'] == 'show'
                library = plex.get("/library/sections/#{element['key']}/all")
                library['MediaContainer']['Directory'].each do | element |
                    tv_episodes = self.getTVInfo(element, tv_episodes)
                end
            end
        end
 
        tv_episodes[:new].sort_by! { |hsh| hsh[:series_name] }
        tv_episodes[:seasons].sort_by! { |hsh| hsh[:series_name] }
        return tv_episodes
    end
```
my config.yaml file with personal data blanked:

```
email:
        title: 'Novedades de la semana'
plex:
        server: localhost
        api_key: ******
mail:
        address: smtp.****.com
        port: 25
        username: alert@****.com
        password: ****
        from: MoviesServer
        subject: 'Novedades de la semana - '
        recipients_email: ['****@me.com']
        recipients: ['****', '****']
```
Sorry for my English
