### ISSUE TITLE
Error: /opt/plexReport/bin/plexReport.rb:183:in `block in getTVEpisodes': undefined method `each' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by StevenDTX** [bstascavage/plexReport#39]
When running **`/opt/plexReport/bin/plexReport.rb -t -v`** I get this error:

```
/opt/plexReport/bin/plexReport.rb:183:in 'block in 'getTVEpisodes': undefined method 'each' for nil:NilClass (NoMethodError)
   from /opt/plexReport/bin/plexReport.rb:180:in 'each'
   from /opt/plexReport/bin/plexReport.rb:180:in 'getTVEpisodes'
   from /opt/plexReport/bin/plexReport.rb:322:in 'main'
   from /opt/plexReport/bin/plexReport.rb:340:in '`<main>'

```

Thanks for your help in getting this resolved. I'm really looking forward to using this.

Here are my config file. I need to figure how to upload a whole log file.

**config.yaml:**
```
---
email:
   title: 'Plex Weekly Updates'
plex:
   server: 10.1.1.20
   api_key: <api>
mail:
   address: smtp.gmail.com
   port: 587
   username: ***@gmail.com
   password: ***
   from: ***@gmail.com 
   subject: 'Plex'
   recipients_email: ['***@***.org', '***@***.org']
   recipients: ['PLEX_USER']

```
